name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy scipy
      
    - name: Init testing
      run: |
        cat > temp_code.py << 'EOF'
        import os
        import sys
        
        parent_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../testing'))
        sys.path.insert(0, parent_dir)
        EOF
        cat lab5/bandc.py >> temp_code.py
        cat temp_code.py
        mv temp_code.py lab5/bandc.py

    - name: Run test
      run: |
        pytest -v
